env:
  global:
    secure: "RMQL+sTCtRJyfLA3+QrRPKxsTUzvCVjzo/UY1xLGssLE/EElPswABNcUNxpM8B5DDoq7xq8WpYBCrzE9QA5U3cZ4sRZ6OXblCxUz4Kj2eaulw+C2zNppBGDSlJwL3S8Vjt/ox38o1zGEkfh1BNwUgbBrxxeBpwWKuzatj3sUKjjyXX+bDzgsj4Um183d/6anrEMaX3RW9AiKgkHQGT7pPQNsXH+T2/XkuZoub7PSO7dkP+sWNlBEdANPwt+O2j+n5Q1J1mWIRVNbY4aKlZJWFSSKic/G2GyaAd3drQe0hR8XLZaTUv6xz081KYVrvoA5YkGQYwsU/EmesihNxuNOY27NVZxtPTjQmjSEr2wtl2Dtpjrl6A6msVO3Q19R8pYoyaBHCgUqmvQ4iRP6lLaARX335wXogfy9FH0XIp9M2sfkXZeJuMj9XO6wj9oV6apnnAnetpuSqrtcuZaLfkONLmUNHbq2/CPAcW4AexmIU8fy4jQzAmJagJnIM2L9viyd9w3hnKy17r92tLSQp9+h8u8LCmr+w443HUqt0kUb11Hcfz+fd9WI0dY0NzsjN7cJffN6pqk6FY2VhserXRvetLhmzXm7H/a/zVKwk6AQhBGNEvqFv9NCUxzm4RHN/kEPWh6Yp/R5KjYZAR9ntVVcMCGcfSpaqki7IkVLXexUn6A="

language: python

matrix:
  fast_finish: true
  include:
  - language: python
    python: 3.5
    os: linux
    dist: trusty
  - language: python
    python: 2.7
    os: linux
    dist: trusty

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      pip install --upgrade pip;
      pip install -e .;
    fi;

before_script:
  cd "$TRAVIS_BUILD_DIR";
  export PYTHONPATH=$PYTHONPATH:$(pwd);

script:
  - pytest

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
      python -m pip install sphinx;
      cd docs;
      make html;
      cd ..;
    fi;

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local_dir: docs/_build
    on:
      branch: master
      python: 3.5

